name: file-editor

services:
  app:
    image: ghcr.io/lxjxxxxxxxx/file-editor:latest
    container_name: file-editor
    ports:
      - "3002:3002"
    volumes:
      - ./config:/app/config
    restart: unless-stopped
